project:
  type: website
  output-dir: docs
  resources: 
    - pubs
  references:
    - type: file
      path: pubs/shark_ray/sharks_and_rays.qmd
      title: "Shark and ray ecology and conservation"
    - type: file
      path: pubs/fish_mgmt/fisheries_mgmt.qmd
      title: "Fisheries Management"
    - type: file
      path: pubs/trade/wildlife_trade.qmd
      title: "Wildlife Trade"

website:
  title: "Leonardo Manir Feitosa"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - research.qmd
      - publications.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    page-layout: full

editor: visual

