---
title: "Teaching"
---

# Courses taught as Teaching Assistant

**Ecology of Managed Ecosystems - ESM201.** Graduate level, Winter 2023, 2024, 2025, Bren School, UCSB.

[Student evaluations](evals/ESM201 - Evaluations.pdf)

*Student comments: I appreciated how thoroughly we went over concepts, equations, and graphs in each section. I felt like it provided good organization and structure to all the concepts we learned in lecture, and helped us identify what was most important to remember. I also really appreciated the midterm review session, I found it to be extremely helpful!*

**Environmental Biogeochemistry - ESM202.** Graduate level, Spring 2025, Bren School, UCSB.

[Student evaluations](evals/ESM202 - Evaluations.pdf)

*Student comments: Leo is the best TA I've had at Bren. I was fortunate to have him as my TA in Ecology as well. He is very accommodating to student learning preferences. I think our section could be more successful if the exam information were articulated to him. There is so much content in this course; in fact, I think it should be two separate courses. It isn't easy to know what to focus on in such a short time. We learned the hard way that we're expected to know minor details during exams and homework. It would be beneficial for Leo to be provided with "key topics." This would make the section less overwhelming. Thank you, Leo, for making the best of this class!! We were lucky to have your support!*

**Statistics for Environmental Data Science - EDS222.** Graduate level, Fall 2024, Bren School, UCSB.

[Student evaluations](evals/EDS222-Fall2024.pdf)

*Student comments: There was a bit of troubleshooting with this class since it was the professors first time teaching the class. Leo was very adaptable and made a comfortable working environment. It seemed like Leo and the professor weren't always on the same page, but Leo would always follow up to address our questions.*

**Introductory Biological Anthropology** Undergraduate level, Fall 2023, UCSB.

[Student evaluations](evals/Anth5 - Evaluations.pdf)

*Student comments: Very kind guy who offered a lot of good, helpful feedback. Not many people attended his sections, but he made the best out of it and took the time to break down certain topics.*
